#!/usr/bin/env bash
# Test script for --agents functionality

echo "Testing --agents command-line argument..."
echo ""
echo "Test 1: Using --agents with AspirationNegotiator"
echo "Command: hani-app --agents 'AspirationNegotiator' --port 5010"
echo ""
echo "Expected behavior:"
echo "  - Should see: 🤖 Using agent types: AspirationNegotiator"
echo "  - Should see: 📋 Command-line agents override: ['AspirationNegotiator']"
echo "  - In UI: 'Command Line/Env' checkbox should be enabled and checked"
echo "  - In UI: Other negotiator checkboxes should be unchecked by default"
echo ""
echo "Test 2: Using --agents with multiple negotiators"
echo "Command: hani-app --agents 'AspirationNegotiator,helpers.AgentK,LLMHybridNegotiator' --port 5010"
echo ""
echo "Expected behavior:"
echo "  - Should see: 🤖 Using agent types: AspirationNegotiator,helpers.AgentK,LLMHybridNegotiator"
echo "  - Should see: 📋 Command-line agents override: ['AspirationNegotiator', 'helpers.AgentK', 'LLMHybridNegotiator']"
echo ""
echo "Test 3: Using HANI_AGENT_TYPES environment variable"
echo "Command: export HANI_AGENT_TYPES='BoulwareTBNegotiator,ConcederTBNegotiator' && hani-app --port 5010"
echo ""
echo "Expected behavior:"
echo "  - Should use environment variable agents"
echo "  - In UI: 'Command Line/Env' checkbox should be enabled and checked"
echo ""
echo "Test 4: Command-line overrides environment variable"
echo "Command: export HANI_AGENT_TYPES='BoulwareTBNegotiator' && hani-app --agents 'AspirationNegotiator' --port 5010"
echo ""
echo "Expected behavior:"
echo "  - Should see: 📋 Command-line agents override: ['AspirationNegotiator']"
echo "  - Command-line should take precedence over env var"
echo ""
echo "Manual testing required - run the commands above and verify the behavior"
